# Follow chemicals through thyroid-related pathways

The following notebook showcases how to use the `rdfsolve.client_api` to explore
the AOPWiki RDF SPARQL endpoint and answer three research questions:

- Which chemicals appear in thyroid-related pathways?
- What names and identifiers do they have?
- Which other pathways and key events are linked to them?

## Open AOPWiki

`explore()` reads the available classes and fields, then gives us a typed Python API to query them.

In [1]:
from rdfsolve.client_api import explore

data = explore(
    "https://aopwiki.rdf.bigcat-bioinformatics.org/sparql",
    graph="http://aopwiki.org/",
)

In [2]:
data.types()

                                 Class
0                             Activity
1              Adverse Outcome Pathway
2                     Biological event
3                  CAS registry number
4                            Cell-term
5                    Ch EBI identifier
6                   Ch EMBL identifier
7               Chem Spider identifier
8                 Drug Bank identifier
9                      Ensembl gene ID
10                              Entity
11                      Gene ID (HGNC)
12                      Gene ID (NCBI)
13                     Gene identifier
14                           Go0008150
15                     HMDB identifier
16                     KEGG identifier
17                           Key Event
18              Key Event Relationship
19               Lipid Maps identifier
20                          Organ-term
21  Pub Chem compound identifier (CID)
22                            Stressor
23                         Uni Prot ID
24                 Wikidata identifier
25                  cellular organisms
26                     chemical entity
27             physical object quality

In [3]:
from IPython.display import Markdown, display

display(Markdown(data.diagram("Adverse outcome pathway", "Stressor", "Chemical entity", "Key event")))

```mermaid
classDiagram
direction LR
    class C0 {
    }
    class C1 {
    }
    class C2 {
    }
    class C3 {
    }
class C0["Adverse Outcome Pathway<br/>http://aopkb.org/aop_ontology#35;AdverseOutcomePathway"]
class C1["Stressor<br/>http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#35;C54571"]
class C2["chemical entity<br/>http://semanticscience.org/resource/CHEMINF_000000"]
class C3["Key Event<br/>http://aopkb.org/aop_ontology#35;KeyEvent"]
C0 --> C1 : Stressor
C0 --> C3 : has adverse outcome
C0 --> C3 : has key event
C0 --> C3 : has molecular initiating event
C1 --> C0 : is part of
C1 --> C2 : has chemical entity
C2 --> C1 : is part of
C3 --> C0 : is part of
```

## Get one pathway by identifier

Already know the pathway identifier? `get()` reads that exact record, without a text search. Use its full identifier URL.

`AOP` is the generated class; `aop` is pathway 162, with its fields filled from AOPWiki.

In [ ]:
AOP = data.model("Adverse outcome pathway")
aop = data.get(AOP, "https://identifiers.org/aop/162")
print(aop.title)

['Enhanced hepatic clearance of thyroid hormones leading to thyroid follicular cell adenomas and carcinomas in the rat and mouse']

Visualizing connections:

In [5]:
nearby = data.connections(aop, max_hops=2, max_paths=1000000)
display(Markdown(data.diagram(paths=nearby, instances=False)))

```mermaid
flowchart LR
N0["Adverse Outcome Pathway<br/>http://aopkb.org/aop_ontology#35;AdverseOutcomePathway"]
N1["Stressor<br/>http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#35;C54571"]
N2["Key Event<br/>http://aopkb.org/aop_ontology#35;KeyEvent"]
N3["Key Event Relationship<br/>http://aopkb.org/aop_ontology#35;KeyEventRelationship"]
N4["cellular organisms<br/>http://purl.bioontology.org/ontology/NCBITAXON/131567"]
N5["No type returned<br/>https://creativecommons.org/licenses/by-sa/4.0/"]
N6["Gene identifier #124; Gene ID #40;HGNC#41;<br/>http://edamontology.org/data_1025 #124; http://edamontology.org/data_2298"]
N7["Cell-term<br/>http://aopkb.org/aop_ontology#35;CellTypeContext"]
N8["Cell-term #124; physical object quality<br/>http://aopkb.org/aop_ontology#35;CellTypeContext #124; http://purl.obolibrary.org/obo/PATO_0001241"]
N9["Organ-term<br/>http://aopkb.org/aop_ontology#35;OrganContext"]
N10["Organ-term #124; physical object quality<br/>http://aopkb.org/aop_ontology#35;OrganContext #124; http://purl.obolibrary.org/obo/PATO_0001241"]
N11["Biological event<br/>http://aopkb.org/aop_ontology#35;BiologicalEvent"]
N12["chemical entity #124; CAS registry number<br/>http://semanticscience.org/resource/CHEMINF_000000 #124; http://semanticscience.org/resource/CHEMINF_000446"]
N13["Go0008150<br/>http://purl.obolibrary.org/obo/GO_0008150"]
N14["physical object quality<br/>http://purl.obolibrary.org/obo/PATO_0001241"]
N15["Dataset #124; Dataset<br/>http://rdfs.org/ns/void#35;Dataset #124; http://www.w3.org/ns/dcat#35;Dataset"]
N16["Dataset<br/>http://rdfs.org/ns/void#35;Dataset"]
N0 -->|"Stressor"| N1
N0 -->|"cellular organisms"| N4
N0 -->|"has adverse outcome"| N2
N0 -->|"has key event"| N2
N0 -->|"has key event relationship"| N3
N0 -->|"identifier"| N0
N0 -->|"license"| N5
N0 -->|"page"| N0
N0 -->|"see also"| N0
N1 -->|"has chemical entity"| N12
N1 -->|"identifier"| N1
N1 -->|"is part of"| N0
N1 -->|"page"| N1
N12 -->|"is part of"| N1
N15 -->|"license"| N5
N16 -->|"license"| N5
N2 -->|"Cell-term"| N7
N2 -->|"Cell-term"| N8
N2 -->|"GO 0008150"| N13
N2 -->|"Gene identifier"| N6
N2 -->|"Organ-term"| N10
N2 -->|"Organ-term"| N9
N2 -->|"cellular organisms"| N4
N2 -->|"gene detected by BERN2 NER#43;EL #40;featured recall-extending method#41;"| N6
N2 -->|"gene detected by HGNC dictionary regex #40;baseline method#41;"| N6
N2 -->|"has biological event"| N11
N2 -->|"identifier"| N2
N2 -->|"is part of"| N0
N2 -->|"page"| N2
N2 -->|"physical object quality"| N14
N2 -->|"physical object quality"| N8
N2 -->|"see also"| N2
N3 -->|"cellular organisms"| N4
N3 -->|"has downstream key event"| N2
N3 -->|"has upstream key event"| N2
N3 -->|"identifier"| N3
N3 -->|"is part of"| N0
N3 -->|"page"| N3
N3 -->|"see also"| N3
N4 -->|"identifier"| N4
```

## Text search

`find()` searches names and identifiers. `types()` shows the classes of the matches.

In [6]:
matches = data.find("thyroid")
matches.types()

,Class,Matches,Example
0,Adverse Outcome Pathway,18,Inhibition of thyroid peroxidase leading to fo...
1,Cell-term,1,thyroid follicular cell
2,Key Event,11,"Increased, Thyroid-stimulating hormone (TSH)"
3,Organ-term,2,thyroid gland
4,Go0008150,2,thyroid hormone generation
5,physical object quality,4,thyroid hormone

`of_type()` selects matches by the specified type:

In [7]:
pathways = matches.of_type("Adverse Outcome Pathway")
pathways

18 matches
                                                                                                                                                      Name                   Class
                                                    Inhibition of thyroid peroxidase leading to follicular cell adenomas and carcinomas (in rat and mouse) Adverse Outcome Pathway
                                                                                                           Kidney dysfunction by decreased thyroid hormone Adverse Outcome Pathway
                                   Interference with thyroid serum binding protein transthyretin and subsequent adverse human neurodevelopmental toxicity  Adverse Outcome Pathway
                            Enhanced hepatic clearance of thyroid hormones leading to thyroid follicular cell adenomas and carcinomas in the rat and mouse Adverse Outcome Pathway
                                                                                    Inhibition of thyroid peroxidase leading to impaired fertility in fish Adverse Outcome Pathway
                                                                 Thyroid Receptor Antagonism and Subsequent Adverse Neurodevelopmental Outcomes in Mammals Adverse Outcome Pathway
                                    Competitive binding to thyroid hormone carrier protein transthyretin (TTR) leading to altered amphibian metamorphosis  Adverse Outcome Pathway
                          Competitive binding to thyroid hormone carrier protein thyroid binding globulin (TBG) leading to altered amphibian metamorphosis Adverse Outcome Pathway
                                                                                 AOP for thyroid disorder caused by triphenyl phosphate via TRβ activation Adverse Outcome Pathway
                                            Thyroid peroxidase (TPO) inhibition leads to periventricular heterotopia formation in the developing rat brain Adverse Outcome Pathway
                                                        AhR activation in the thyroid leading to Subsequent Adverse Neurodevelopmental Outcomes in Mammals Adverse Outcome Pathway
Bisphenol A analogs induce cellular dysfunction in human trophoblast cells in a thyroid hormone receptor-dependent manner: in silico and in vitro analyses Adverse Outcome Pathway
                           Thyroid hormone antagonism leading to impaired oligodendrocyte maturation during development and subsequent decreased cognition Adverse Outcome Pathway
                                                                Thyroid Peroxidase Inhibition Leading to Reduced, Swimming Performance via Hypomyelination Adverse Outcome Pathway
                                                                       Thyroid Hormone Excess Leading to Reduced, Swimming Performance via Hypomyelination Adverse Outcome Pathway
     Decreased thyroid hormone levels in the brain regulated via transport, metabolism and TR activation leading to decreased cognition and motor function Adverse Outcome Pathway
                            Decreased thyroid hormone receptor beta transcriptional activity leading to MASLD progression via endoplasmic reticulum stress Adverse Outcome Pathway
     Upregulation of Thyroid Hormone Catabolism via Activation of Hepatic Nuclear Receptors, and Subsequent Adverse Neurodevelopmental Outcomes in Mammals Adverse Outcome Pathway

`paths()` lists the links between the result classes.

In [8]:
pathways.paths()

,From,Link,To
0,Adverse Outcome Pathway,has key event,Key Event
1,Adverse Outcome Pathway,has molecular initiating event,Key Event
2,Adverse Outcome Pathway,cellular organisms,cellular organisms
3,Adverse Outcome Pathway,see also,Adverse Outcome Pathway
4,Adverse Outcome Pathway,identifier,Adverse Outcome Pathway
5,Adverse Outcome Pathway,has adverse outcome,Key Event
6,Adverse Outcome Pathway,has key event relationship,Key Event Relationship
7,Adverse Outcome Pathway,page,Adverse Outcome Pathway
8,Adverse Outcome Pathway,Stressor,Stressor

`paths_between()` lists paths between two classes.

In [9]:
from IPython.display import Markdown, display

routes = data.paths_between("Adverse outcome pathway", "Chemical entity", max_hops=2)
display(routes)
display(Markdown(data.diagram(paths=routes)))

,Path,Step,From,Link,Direction,To
0,1,1,Adverse Outcome Pathway,Stressor,→,Stressor
1,1,2,Stressor,has chemical entity,→,chemical entity
2,2,1,Adverse Outcome Pathway,Stressor,→,Stressor
3,2,2,Stressor,is part of,←,chemical entity
4,3,1,Adverse Outcome Pathway,is part of,←,Stressor
5,3,2,Stressor,has chemical entity,→,chemical entity
6,4,1,Adverse Outcome Pathway,is part of,←,Stressor
7,4,2,Stressor,is part of,←,chemical entity

```mermaid
flowchart LR
N0["Adverse Outcome Pathway<br/>http://aopkb.org/aop_ontology#35;AdverseOutcomePathway"]
N1["Stressor<br/>http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#35;C54571"]
N2["chemical entity<br/>http://semanticscience.org/resource/CHEMINF_000000"]
N0 -->|"Stressor"| N1
N1 -->|"has chemical entity"| N2
N1 -->|"is part of"| N0
N2 -->|"is part of"| N1
```

## Follow the stressor annotations

`related()` follows links to records of the specified class.

In [10]:
stressors = pathways.related("Stressor")
stressors

24 matches
                                      Name    Class
                             Phenobarbital Stressor
                  Polychlorinated biphenyl Stressor
                       Halogenated phenols Stressor
                                 thiazopyr Stressor
                Pyrethrins and Pyrethroids Stressor
2,3,7,8-tetrachlorodibenzo-p-dioxin (TCDD) Stressor
                         Ethylene thiourea Stressor
            Polychlorinated dibenzodioxins Stressor
            Polybrominated diphenyl ethers Stressor
                               Isoflavones Stressor
                  Perflourinated chemicals Stressor
                                Phthalates Stressor
                     Tetrabromobisphenol A Stressor
                                  Clonixin Stressor
                         Meclofenamic acid Stressor
                      2,6-dinitro-p-cresol Stressor
                                 Triclopyr Stressor
                               Methimazole Stressor
                          Propylthiouracil Stressor
                       Triphenyl phosphate Stressor

## Get the chemicals and their identifiers

`via="Stressor"` takes us through stressors to chemicals. `show()` displays the fields we ask for, alongside each record’s name and class.

In [11]:
chemicals = pathways.related(kind="Chemical entity", via="Stressor")
chemicals.show("identifier")

,Name,Class,Identifier
0,Triphenyl phosphate,chemical entity,https://identifiers.org/cas/115-86-6
1,Thiazopyr,chemical entity,https://identifiers.org/cas/117718-60-2
2,"2,2',4,4'-Tetrahydroxybenzophenone",chemical entity,https://identifiers.org/cas/131-55-5
3,Clonixin,chemical entity,https://identifiers.org/cas/17737-65-4
4,Phenobarbital,chemical entity,https://identifiers.org/cas/50-06-6
5,6-Propyl-2-thiouracil,chemical entity,https://identifiers.org/cas/51-52-5
6,Triclopyr,chemical entity,https://identifiers.org/cas/55335-06-3
7,Methimazole,chemical entity,https://identifiers.org/cas/60-56-0
8,Meclofenamic acid,chemical entity,https://identifiers.org/cas/644-62-2
9,"3,3',5,5'-Tetrabromobisphenol A",chemical entity,https://identifiers.org/cas/79-94-7
10,Ethylene thiourea,chemical entity,https://identifiers.org/cas/96-45-7

## Look up a name from the list

`value="Phenobarbital"` looks for that name among connected records. `show()` lets us read their other identifiers.

In [12]:
phenobarbital = pathways.related(value="Phenobarbital", via="Stressor").of_type("Chemical entity")
phenobarbital.show("exactmatch")

,Name,Class,Exactmatch
0,Phenobarbital,chemical entity,https://identifiers.org/chebi/8069 | https://i...

Another option is to find the paths between a given Adverse Outcome Pathway and any chemical compound:

In [13]:
ex_pathway = pathways[2]
print(ex_pathway.uri,
      ex_pathway.title,
      type(ex_pathway))

https://identifiers.org/aop/152 ['Interference with thyroid serum binding protein transthyretin and subsequent adverse human neurodevelopmental toxicity '] <class 'rdfsolve.generated.AdverseOutcomePathway'>

In [14]:
name_paths = data.paths_between(
    source=ex_pathway, target="chemical entity", max_hops=3
)
display(name_paths)
display(Markdown(data.diagram(paths=name_paths)))

,Path,Step,From,From class,Link,Direction,To,To class
0,1,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/74,Stressor
1,1,2,https://identifiers.org/aop.stressor/74,Stressor,has chemical entity,→,https://identifiers.org/cas/131-55-5,chemical entity | CAS registry number
2,2,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/262,Stressor
3,2,2,https://identifiers.org/aop.stressor/262,Stressor,has chemical entity,→,https://identifiers.org/cas/17737-65-4,chemical entity | CAS registry number
4,3,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/265,Stressor
5,3,2,https://identifiers.org/aop.stressor/265,Stressor,has chemical entity,→,https://identifiers.org/cas/55335-06-3,chemical entity | CAS registry number
6,4,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/263,Stressor
7,4,2,https://identifiers.org/aop.stressor/263,Stressor,has chemical entity,→,https://identifiers.org/cas/644-62-2,chemical entity | CAS registry number
8,5,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/261,Stressor
9,5,2,https://identifiers.org/aop.stressor/261,Stressor,has chemical entity,→,https://identifiers.org/cas/79-94-7,chemical entity | CAS registry number
10,6,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/74,Stressor
11,6,2,https://identifiers.org/aop.stressor/74,Stressor,is part of,←,https://identifiers.org/cas/131-55-5,chemical entity | CAS registry number
12,7,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/262,Stressor
13,7,2,https://identifiers.org/aop.stressor/262,Stressor,is part of,←,https://identifiers.org/cas/17737-65-4,chemical entity | CAS registry number
14,8,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/265,Stressor
15,8,2,https://identifiers.org/aop.stressor/265,Stressor,is part of,←,https://identifiers.org/cas/55335-06-3,chemical entity | CAS registry number
16,9,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/263,Stressor
17,9,2,https://identifiers.org/aop.stressor/263,Stressor,is part of,←,https://identifiers.org/cas/644-62-2,chemical entity | CAS registry number
18,10,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,Stressor,→,https://identifiers.org/aop.stressor/261,Stressor
19,10,2,https://identifiers.org/aop.stressor/261,Stressor,is part of,←,https://identifiers.org/cas/79-94-7,chemical entity | CAS registry number
20,11,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/74,Stressor
21,11,2,https://identifiers.org/aop.stressor/74,Stressor,has chemical entity,→,https://identifiers.org/cas/131-55-5,chemical entity | CAS registry number
22,12,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/262,Stressor
23,12,2,https://identifiers.org/aop.stressor/262,Stressor,has chemical entity,→,https://identifiers.org/cas/17737-65-4,chemical entity | CAS registry number
24,13,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/265,Stressor
25,13,2,https://identifiers.org/aop.stressor/265,Stressor,has chemical entity,→,https://identifiers.org/cas/55335-06-3,chemical entity | CAS registry number
26,14,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/263,Stressor
27,14,2,https://identifiers.org/aop.stressor/263,Stressor,has chemical entity,→,https://identifiers.org/cas/644-62-2,chemical entity | CAS registry number
28,15,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/261,Stressor
29,15,2,https://identifiers.org/aop.stressor/261,Stressor,has chemical entity,→,https://identifiers.org/cas/79-94-7,chemical entity | CAS registry number
30,16,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/261,Stressor
31,16,2,https://identifiers.org/aop.stressor/261,Stressor,is part of,←,https://identifiers.org/cas/79-94-7,chemical entity | CAS registry number
32,17,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/262,Stressor
33,17,2,https://identifiers.org/aop.stressor/262,Stressor,is part of,←,https://identifiers.org/cas/17737-65-4,chemical entity | CAS registry number
34,18,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/263,Stressor
35,18,2,https://identifiers.org/aop.stressor/263,Stressor,is part of,←,https://identifiers.org/cas/644-62-2,chemical entity | CAS registry number
36,19,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/265,Stressor
37,19,2,https://identifiers.org/aop.stressor/265,Stressor,is part of,←,https://identifiers.org/cas/55335-06-3,chemical entity | CAS registry number
38,20,1,https://identifiers.org/aop/152,Adverse Outcome Pathway,is part of,←,https://identifiers.org/aop.stressor/74,Stressor
39,20,2,https://identifiers.org/aop.stressor/74,Stressor,is part of,←,https://identifiers.org/cas/131-55-5,chemical entity | CAS registry number

```mermaid
flowchart LR
N0["Adverse Outcome Pathway<br/>https://identifiers.org/aop/152"]
N1["Stressor<br/>https://identifiers.org/aop.stressor/74"]
N2["chemical entity #124; CAS registry number<br/>https://identifiers.org/cas/131-55-5"]
N3["Stressor<br/>https://identifiers.org/aop.stressor/262"]
N4["chemical entity #124; CAS registry number<br/>https://identifiers.org/cas/17737-65-4"]
N5["Stressor<br/>https://identifiers.org/aop.stressor/265"]
N6["chemical entity #124; CAS registry number<br/>https://identifiers.org/cas/55335-06-3"]
N7["Stressor<br/>https://identifiers.org/aop.stressor/263"]
N8["chemical entity #124; CAS registry number<br/>https://identifiers.org/cas/644-62-2"]
N9["Stressor<br/>https://identifiers.org/aop.stressor/261"]
N10["chemical entity #124; CAS registry number<br/>https://identifiers.org/cas/79-94-7"]
N0 -->|"Stressor"| N1
N0 -->|"Stressor"| N3
N0 -->|"Stressor"| N5
N0 -->|"Stressor"| N7
N0 -->|"Stressor"| N9
N1 -->|"has chemical entity"| N2
N1 -->|"is part of"| N0
N10 -->|"is part of"| N9
N2 -->|"is part of"| N1
N3 -->|"has chemical entity"| N4
N3 -->|"is part of"| N0
N4 -->|"is part of"| N3
N5 -->|"has chemical entity"| N6
N5 -->|"is part of"| N0
N6 -->|"is part of"| N5
N7 -->|"has chemical entity"| N8
N7 -->|"is part of"| N0
N8 -->|"is part of"| N7
N9 -->|"has chemical entity"| N10
N9 -->|"is part of"| N0
```

And the AOP to a specific chemical entity, by its name:

In [22]:
name_paths = data.paths_between(
    source=ex_pathway, target_value="Tetrabromobisphenol A", max_hops=3
)
display(Markdown(data.diagram(paths=name_paths)))

```mermaid
flowchart LR
N0["Adverse Outcome Pathway<br/>https://identifiers.org/aop/152"]
N1["Stressor<br/>https://identifiers.org/aop.stressor/261"]
N2["chemical entity #124; CAS registry number<br/>https://identifiers.org/cas/79-94-7"]
N3["Pub Chem compound identifier #40;CID#41;<br/>https://identifiers.org/pubchem.compound/6618"]
N4["Chem Spider identifier<br/>https://identifiers.org/chemspider/6366"]
N5["Ch EBI identifier<br/>https://identifiers.org/chebi/33217"]
N6["KEGG identifier<br/>https://identifiers.org/kegg.compound/C13620"]
N7["Ch EMBL identifier<br/>https://identifiers.org/chembl.compound/CHEMBL184450"]
N8["Wikidata identifier<br/>https://identifiers.org/wikidata/Q425246"]
N0 -->|"Stressor"| N1
N1 -->|"has chemical entity"| N2
N1 -->|"is part of"| N0
N2 -->|"exactMatch"| N3
N2 -->|"exactMatch"| N4
N2 -->|"exactMatch"| N5
N2 -->|"exactMatch"| N6
N2 -->|"exactMatch"| N7
N2 -->|"exactMatch"| N8
N2 -->|"is part of"| N1
N2 -->|"same as"| N3
N2 -->|"same as"| N4
N2 -->|"same as"| N5
N2 -->|"same as"| N6
N2 -->|"same as"| N7
N2 -->|"same as"| N8
```

## How is this chemical connected?

First, list the pathways linked to Phenobarbital.

In [16]:
phenobarbital_pathways = phenobarbital.related("Stressor").related("Adverse outcome pathway")
phenobarbital_pathways

2 matches
                                                                                                                          Name                   Class
        Constitutive androstane receptor activation leading to hepatocellular adenomas and carcinomas in the mouse and the rat Adverse Outcome Pathway
Enhanced hepatic clearance of thyroid hormones leading to thyroid follicular cell adenomas and carcinomas in the rat and mouse Adverse Outcome Pathway

`connections()` shows the actual records and links between two choices. `[0]` picks the first record from each list. We allow up to two links, without revisiting a record.

Below: the first row, the first complete path, then the same path as classes. One row is one link; a path can contain several links.

In [17]:
connections = data.connections(phenobarbital[0], phenobarbital_pathways[0], max_hops=2)
display(connections.head(1))
display(Markdown(data.diagram(paths=connections, path=1)))
display(Markdown(data.diagram(paths=connections, path=1, instances=False)))

,Path,Step,From,From class,Link,Direction,To,To class
0,1,1,https://identifiers.org/cas/50-06-6,chemical entity | CAS registry number,is part of,→,https://identifiers.org/aop.stressor/133,Stressor

```mermaid
flowchart LR
N0["chemical entity #124; CAS registry number<br/>https://identifiers.org/cas/50-06-6"]
N1["Stressor<br/>https://identifiers.org/aop.stressor/133"]
N2["Adverse Outcome Pathway<br/>https://identifiers.org/aop/107"]
N0 -->|"is part of"| N1
N1 -->|"is part of"| N2
```

```mermaid
flowchart LR
N0["chemical entity #124; CAS registry number<br/>http://semanticscience.org/resource/CHEMINF_000000 #124; http://semanticscience.org/resource/CHEMINF_000446"]
N1["Stressor<br/>http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#35;C54571"]
N2["Adverse Outcome Pathway<br/>http://aopkb.org/aop_ontology#35;AdverseOutcomePathway"]
N0 -->|"is part of"| N1
N1 -->|"is part of"| N2
```

Which other pathways have these chemicals as stressors?

In [18]:
annotations = chemicals.related("Stressor")
other_pathways = annotations.related("Adverse outcome pathway").without(pathways)
other_pathways

8 matches
                                                                                                                  Name                   Class
Constitutive androstane receptor activation leading to hepatocellular adenomas and carcinomas in the mouse and the rat Adverse Outcome Pathway
                 Thyroperoxidase inhibition leading to increased mortality via reduced anterior swim bladder inflation Adverse Outcome Pathway
                                                 Thyroperoxidase inhibition leading to altered amphibian metamorphosis Adverse Outcome Pathway
                     Thyroperoxidase inhibition leading to altered visual function via altered retinal layer structure Adverse Outcome Pathway
                G protein-coupled estrogen receptor 1 (GPER) signal pathway in the lipid metabolism disrupting effects Adverse Outcome Pathway
                           Inhibition of Thyroperoxidase and Subsequent Adverse Neurodevelopmental Outcomes in Mammals Adverse Outcome Pathway
        SULT1E1 inhibition leading to uterine adenocarcinoma via increased estrogen availability at target organ level Adverse Outcome Pathway
                         17β-Hydroxysteroid dehydrogenase 2, inhibition leading to activation, estrogen receptor alpha Adverse Outcome Pathway

See the key events in those pathways

In [19]:
events = other_pathways.related("Key event", via="has key event")
events

35 matches
                                                           Name     Class
                               Decreased, Triiodothyronine (T3) Key Event
                                  Reduced, Swimming performance Key Event
                       Reduced, Anterior swim bladder inflation Key Event
                            Activation, estrogen receptor alpha Key Event
                               Altered, Amphibian metamorphosis Key Event
Altered gene expression specific to CAR activation, Hepatocytes Key Event
                                          Up Regulation, SREBF2 Key Event
                                                Activation, AKT Key Event
                                             Activation, mTORC1 Key Event
                                               Activation, PI3K Key Event
                                      Increase, Steatohepatitis Key Event
                                       Altered, Visual function Key Event
                               Altered, retinal layer structure Key Event
                                      Abnormal lipid metabolism Key Event
          protein-coupled estrogen receptor 1 (GPER) activation Key Event
                    Inhibition of Sulfotransferase E1 (SULT1E1) Key Event
                 17β-Hydroxysteroid dehydrogenase 2, inhibition Key Event
                              Estradiol availability, increased Key Event
                                              Activation, PPARα Key Event
                           Thyroid hormone synthesis, Decreased Key Event

## Keep the results

Save the chemical table and the record of how we found it.

In [20]:
chemicals.show("identifier").to_csv("thyroid-chemicals.csv", index=False)
data.save_session("thyroid-session.json")
data.close()

Next: [keep a small dataset](02_subset.ipynb) or [turn the chemical table into RDF](03_to_RDF_schema.ipynb).

## Queries

These results are also in `thyroid-session.json`.

In [21]:
data.query_log()

QueryLog(146 executions; open in a notebook to view results)